# frozen_string_literal: true

# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2025 The Linux Foundation

source 'https://rubygems.org'

ruby '3.2.2'

# Core framework
gem 'rails', '~> 7.1.0'

# Database
gem 'pg', '>= 1.1'

# Web server
gem 'puma', '~> 6.0'

# Performance
gem 'bootsnap', '>= 1.4.4', require: false

# Authentication
gem 'devise', '~> 4.9'

# Authorization
gem 'pundit', '~> 2.3'

# Background jobs
gem 'sidekiq', '~> 7.0'

# Caching
gem 'redis', '>= 4.0'

# API
gem 'grape', '~> 2.0'

# Asset pipeline
gem 'sprockets-rails'
gem 'importmap-rails'
gem 'turbo-rails'
gem 'stimulus-rails'

group :development, :test do
  gem 'rspec-rails', '~> 6.0'
  gem 'factory_bot_rails', '~> 6.2'
  gem 'faker', '~> 3.0'
  gem 'pry-byebug'
  gem 'pry-rails'
end

group :development do
  gem 'web-console'
  gem 'rubocop', '~> 1.50', require: false
  gem 'rubocop-rails', '~> 2.19', require: false
  gem 'rubocop-rspec', '~> 2.20', require: false
  gem 'brakeman', require: false
  gem 'bundler-audit', require: false
end

group :test do
  gem 'capybara'
  gem 'selenium-webdriver'
  gem 'webdrivers'
  gem 'shoulda-matchers', '~> 5.0'
  gem 'simplecov', require: false
end

platform :ruby do
  gem 'nokogiri', '>= 1.13'
end

platform :jruby do
  gem 'activerecord-jdbc-adapter'
end

# Bundler version
gem 'bundler', '~> 2.4'
