// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 The Linux Foundation

package javascript

import (
	"encoding/json"
	"fmt"
	"maps"
	"os"
	"path/filepath"
	"slices"
	"strings"
	"testing"
)

const (
	classicYarnLock = "# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.\n" +
		"# yarn lockfile v1\n\n\nleft-pad@^1.3.0:\n  version \"1.3.0\"\n"
	berryYarnLock = "# This file is generated by running \"yarn install\" inside your project.\n" +
		"# Manual changes might be lost - proceed with caution!\n\n" +
		"__metadata:\n  version: 8\n  cacheKey: 10c0\n"
)

// writeProject creates a project directory holding files.
func writeProject(t *testing.T, files map[string]string) string {
	t.Helper()
	dir := t.TempDir()
	for name, content := range files {
		path := filepath.Join(dir, name)
		if err := os.MkdirAll(filepath.Dir(path), 0o750); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(path, []byte(content), 0o600); err != nil {
			t.Fatal(err)
		}
	}
	return dir
}

// detectProject runs package manager detection over a project directory.
func detectProject(t *testing.T, dir string) (packageManager, []string) {
	t.Helper()
	content, err := os.ReadFile(filepath.Join(dir, "package.json"))
	if err != nil {
		t.Fatal(err)
	}
	var pkg PackageJSON
	if err := json.Unmarshal(content, &pkg); err != nil {
		t.Fatal(err)
	}
	return detectPackageManager(dir, &pkg)
}

// Every way a project can name its package manager (a lockfile, the
// packageManager field, devEngines.packageManager, or several together)
// must give the same answer.
func TestPackageManagerConsistency(t *testing.T) {
	managers := []struct {
		name     string
		want     string
		version  string
		lockFile string
		files    map[string]string
	}{
		{"npm package-lock", "npm", "10.9.2", "package-lock.json",
			map[string]string{"package-lock.json": `{"lockfileVersion": 3}`}},
		{"npm shrinkwrap", "npm", "10.9.2", "npm-shrinkwrap.json",
			map[string]string{"npm-shrinkwrap.json": `{"lockfileVersion": 3}`}},
		{"yarn classic", "yarn", "1.22.22", "yarn.lock",
			map[string]string{"yarn.lock": classicYarnLock}},
		{"yarn berry with yarnrc", "yarn-berry", "4.5.0", "yarn.lock",
			map[string]string{"yarn.lock": berryYarnLock, ".yarnrc.yml": "nodeLinker: node-modules\n"}},
		{"yarn berry lockfile only", "yarn-berry", "4.5.0", "yarn.lock",
			map[string]string{"yarn.lock": berryYarnLock}},
		{"yarn 2", "yarn-berry", "2.4.3", "yarn.lock",
			map[string]string{"yarn.lock": berryYarnLock}},
		{"pnpm", "pnpm", "10.18.0", "pnpm-lock.yaml",
			map[string]string{"pnpm-lock.yaml": "lockfileVersion: '9.0'\n"}},
		{"bun text lockfile", "bun", "1.2.23", "bun.lock",
			map[string]string{"bun.lock": `{"lockfileVersion": 1}`}},
		{"bun binary lockfile", "bun", "1.1.38", "bun.lockb",
			map[string]string{"bun.lockb": "binary"}},
	}

	declarations := []struct {
		name        string
		packageJSON string // formatted with the manager name and version
		declares    bool
	}{
		{"no declaration", `{"name": "t"}`, false},
		{"packageManager", `{"name": "t", "packageManager": "%[1]s@%[2]s"}`, true},
		{"packageManager with hash", `{"name": "t", "packageManager": "%[1]s@%[2]s+sha512.0123abcd"}`, true},
		{"devEngines object",
			`{"name": "t", "devEngines": {"packageManager": {"name": "%[1]s", "version": "%[2]s"}}}`, true},
		{"devEngines array",
			`{"name": "t", "devEngines": {"packageManager": [{"name": "%[1]s", "version": "%[2]s", "onFail": "error"}]}}`,
			true},
		{"devEngines with hash",
			`{"name": "t", "devEngines": {"packageManager": {"name": "%[1]s", "version": "%[2]s+sha512.0123abcd"}}}`,
			true},
		{"both fields",
			`{"name": "t", "packageManager": "%[1]s@%[2]s",` +
				` "devEngines": {"packageManager": {"name": "%[1]s", "version": "%[2]s"}}}`, true},
	}

	for _, manager := range managers {
		family := strings.TrimSuffix(manager.want, "-berry")
		for _, declared := range declarations {
			for _, withLockFile := range []bool{true, false} {
				if !declared.declares && !withLockFile {
					continue // nothing names a manager; see TestPackageManagerDefault
				}
				name := fmt.Sprintf("%s/%s/lockfile=%t", manager.name, declared.name, withLockFile)
				t.Run(name, func(t *testing.T) {
					packageJSON := declared.packageJSON
					if declared.declares {
						packageJSON = fmt.Sprintf(packageJSON, family, manager.version)
					}
					files := map[string]string{"package.json": packageJSON}
					wantLockFile, wantVersion := "", ""
					if withLockFile {
						maps.Copy(files, manager.files)
						wantLockFile = manager.lockFile
					}
					if declared.declares {
						wantVersion = manager.version
					}

					got, warnings := detectProject(t, writeProject(t, files))
					if got.name != manager.want {
						t.Errorf("name = %q, want %q", got.name, manager.want)
					}
					if got.version != wantVersion {
						t.Errorf("version = %q, want %q", got.version, wantVersion)
					}
					if got.lockFile != wantLockFile {
						t.Errorf("lockFile = %q, want %q", got.lockFile, wantLockFile)
					}
					if len(warnings) > 0 {
						t.Errorf("unexpected warnings: %q", warnings)
					}
				})
			}
		}
	}
}

func TestPackageManagerDefault(t *testing.T) {
	got, warnings := detectProject(t, writeProject(t, map[string]string{"package.json": `{"name": "t"}`}))
	if got != (packageManager{name: managerNpm}) {
		t.Errorf("got %+v, want npm with no version or lockfile", got)
	}
	if len(warnings) > 0 {
		t.Errorf("unexpected warnings: %q", warnings)
	}
}

// Conflicting signals keep the existing priority (declaration, then pnpm,
// Yarn, npm, Bun lockfiles) and say so.
func TestPackageManagerConflicts(t *testing.T) {
	tests := []struct {
		name         string
		files        map[string]string
		want         packageManager
		wantWarnings []string // substrings, one per expected warning
	}{
		{
			name: "pnpm and npm lockfiles",
			files: map[string]string{
				"package.json":      `{"name": "t"}`,
				"pnpm-lock.yaml":    "lockfileVersion: '9.0'\n",
				"package-lock.json": `{}`,
			},
			want:         packageManager{name: "pnpm", lockFile: "pnpm-lock.yaml"},
			wantWarnings: []string{"more than one package manager are present (pnpm-lock.yaml, package-lock.json); reporting pnpm"},
		},
		{
			name: "yarn and bun lockfiles",
			files: map[string]string{
				"package.json": `{"name": "t"}`,
				"yarn.lock":    berryYarnLock,
				"bun.lock":     `{}`,
			},
			want:         packageManager{name: "yarn-berry", lockFile: "yarn.lock"},
			wantWarnings: []string{"(yarn.lock, bun.lock); reporting yarn-berry"},
		},
		{
			name: "field disagrees with lockfile",
			files: map[string]string{
				"package.json":      `{"name": "t", "packageManager": "pnpm@9.15.0"}`,
				"package-lock.json": `{}`,
			},
			want: packageManager{name: "pnpm", version: "9.15.0"},
			wantWarnings: []string{
				"packageManager names pnpm but no pnpm lockfile is present (found package-lock.json); reporting pnpm",
			},
		},
		{
			name: "devEngines disagrees with lockfile",
			files: map[string]string{
				"package.json": `{"name": "t", "devEngines": {"packageManager": {"name": "bun"}}}`,
				"yarn.lock":    classicYarnLock,
			},
			want:         packageManager{name: "bun"},
			wantWarnings: []string{"devEngines.packageManager names bun but no bun lockfile is present"},
		},
		{
			name: "field matches one of several lockfiles",
			files: map[string]string{
				"package.json":      `{"name": "t", "packageManager": "yarn@4.5.0"}`,
				"yarn.lock":         classicYarnLock,
				"package-lock.json": `{}`,
			},
			want:         packageManager{name: "yarn-berry", version: "4.5.0", lockFile: "yarn.lock"},
			wantWarnings: []string{"(yarn.lock, package-lock.json); reporting yarn-berry"},
		},
		{
			name: "packageManager and devEngines disagree",
			files: map[string]string{
				"package.json": `{"name": "t", "packageManager": "pnpm@10.0.0",` +
					` "devEngines": {"packageManager": {"name": "npm"}}}`,
				"pnpm-lock.yaml": "lockfileVersion: '9.0'\n",
			},
			want:         packageManager{name: "pnpm", version: "10.0.0", lockFile: "pnpm-lock.yaml"},
			wantWarnings: []string{"packageManager names pnpm, which devEngines.packageManager does not list; using pnpm"},
		},
		{
			name: "devEngines alternative matching the lockfile",
			files: map[string]string{
				"package.json": `{"name": "t", "devEngines": {"packageManager":` +
					` [{"name": "bun"}, {"name": "yarn", "version": "^4.0.0"}]}}`,
				"yarn.lock": berryYarnLock,
			},
			want: packageManager{name: "yarn-berry", version: "^4.0.0", lockFile: "yarn.lock"},
		},
		{
			name: "Yarn alternative matching a berry lockfile",
			files: map[string]string{
				"package.json": `{"name": "t", "devEngines": {"packageManager":` +
					` [{"name": "yarn", "version": "1.x"}, {"name": "yarn", "version": "4.x"}]}}`,
				"yarn.lock": berryYarnLock,
			},
			want: packageManager{name: "yarn-berry", version: "4.x", lockFile: "yarn.lock"},
		},
		{
			name: "Yarn alternative matching a classic lockfile",
			files: map[string]string{
				"package.json": `{"name": "t", "devEngines": {"packageManager":` +
					` [{"name": "yarn", "version": "4.x"}, {"name": "yarn", "version": "1.x"}]}}`,
				"yarn.lock": classicYarnLock,
			},
			want: packageManager{name: "yarn", version: "1.x", lockFile: "yarn.lock"},
		},
		{
			name: "unparsable Yarn alternative does not shadow a matching one",
			files: map[string]string{
				"package.json": `{"name": "t", "devEngines": {"packageManager":` +
					` [{"name": "yarn", "version": "stable"}, {"name": "yarn", "version": "4.x"}]}}`,
				"yarn.lock": berryYarnLock,
			},
			want: packageManager{name: "yarn-berry", version: "4.x", lockFile: "yarn.lock"},
		},
		{
			name: "build metadata is not mistaken for a Corepack hash",
			files: map[string]string{
				"package.json":   `{"name": "t", "packageManager": "pnpm@10.18.0+build.7"}`,
				"pnpm-lock.yaml": "lockfileVersion: '9.0'\n",
			},
			want:         packageManager{name: "pnpm", lockFile: "pnpm-lock.yaml"},
			wantWarnings: []string{"packageManager has a version this action cannot report; omitting it"},
		},
		{
			name: "devEngines alternatives without a lockfile use the first",
			files: map[string]string{
				"package.json": `{"name": "t", "devEngines": {"packageManager":` +
					` [{"name": "bun", "version": "1.2.23"}, {"name": "yarn"}]}}`,
			},
			want: packageManager{name: "bun", version: "1.2.23"},
		},
		{
			name: "packageManager matching a later devEngines alternative",
			files: map[string]string{
				"package.json": `{"name": "t", "packageManager": "yarn@4.5.0", "devEngines": {"packageManager":` +
					` [{"name": "bun"}, {"name": "yarn", "version": "3.x"}, {"name": "yarn", "version": "^4.0.0"}]}}`,
				"yarn.lock": berryYarnLock,
			},
			want: packageManager{name: "yarn-berry", version: "4.5.0", lockFile: "yarn.lock"},
		},
		{
			name: "unsupported devEngines alternative beside a supported one",
			files: map[string]string{
				"package.json": `{"name": "t", "devEngines": {"packageManager":` +
					` [{"name": "cnpm"}, {"name": "pnpm", "version": "10.x"}]}}`,
				"pnpm-lock.yaml": "lockfileVersion: '9.0'\n",
			},
			want: packageManager{name: "pnpm", version: "10.x", lockFile: "pnpm-lock.yaml"},
		},
		{
			name: "only unsupported devEngines alternatives",
			files: map[string]string{
				"package.json": `{"name": "t", "devEngines": {"packageManager": [{"name": "cnpm"}]}}`,
			},
			want:         packageManager{name: "npm"},
			wantWarnings: []string{"devEngines.packageManager names an unsupported package manager; ignoring it"},
		},
		{
			name: "packageManager major outside every devEngines alternative",
			files: map[string]string{
				"package.json": `{"name": "t", "packageManager": "pnpm@8.15.0", "devEngines": {"packageManager":` +
					` [{"name": "pnpm", "version": "9.x"}, {"name": "pnpm", "version": "^10.0.0"}]}}`,
				"pnpm-lock.yaml": "lockfileVersion: '9.0'\n",
			},
			want:         packageManager{name: "pnpm", version: "8.15.0", lockFile: "pnpm-lock.yaml"},
			wantWarnings: []string{"packageManager names pnpm 8, which devEngines.packageManager does not allow; using pnpm 8"},
		},
		{
			name: "packageManager major outside the devEngines range",
			files: map[string]string{
				"package.json": `{"name": "t", "packageManager": "pnpm@6.6.2",` +
					` "devEngines": {"packageManager": {"name": "pnpm", "version": "10.x"}}}`,
				"pnpm-lock.yaml": "lockfileVersion: '9.0'\n",
			},
			want: packageManager{name: "pnpm", version: "6.6.2", lockFile: "pnpm-lock.yaml"},
			wantWarnings: []string{
				"packageManager names pnpm 6, which devEngines.packageManager does not allow; using pnpm 6",
			},
		},
		{
			name: "packageManager major below an open devEngines range",
			files: map[string]string{
				"package.json": `{"name": "t", "packageManager": "pnpm@8.15.0",` +
					` "devEngines": {"packageManager": {"name": "pnpm", "version": ">=9"}}}`,
				"pnpm-lock.yaml": "lockfileVersion: '9.0'\n",
			},
			want:         packageManager{name: "pnpm", version: "8.15.0", lockFile: "pnpm-lock.yaml"},
			wantWarnings: []string{"packageManager names pnpm 8, which devEngines.packageManager does not allow"},
		},
		{
			name: "Yarn classic declared against a Berry devEngines range",
			files: map[string]string{
				"package.json": `{"name": "t", "packageManager": "yarn@1.22.22",` +
					` "devEngines": {"packageManager": {"name": "yarn", "version": "^4.0.0"}}}`,
				"yarn.lock": classicYarnLock,
			},
			want:         packageManager{name: "yarn", version: "1.22.22", lockFile: "yarn.lock"},
			wantWarnings: []string{"packageManager names yarn 1, which devEngines.packageManager does not allow"},
		},
		{
			name: "devEngines range admitting the packageManager major",
			files: map[string]string{
				"package.json": `{"name": "t", "packageManager": "pnpm@9.15.0",` +
					` "devEngines": {"packageManager": {"name": "pnpm", "version": ">=8 <10"}}}`,
				"pnpm-lock.yaml": "lockfileVersion: '9.0'\n",
			},
			want: packageManager{name: "pnpm", version: "9.15.0", lockFile: "pnpm-lock.yaml"},
		},
		{
			name: "devEngines range this cannot parse is not checked",
			files: map[string]string{
				"package.json": `{"name": "t", "packageManager": "pnpm@9.15.0",` +
					` "devEngines": {"packageManager": {"name": "pnpm", "version": "latest"}}}`,
				"pnpm-lock.yaml": "lockfileVersion: '9.0'\n",
			},
			want: packageManager{name: "pnpm", version: "9.15.0", lockFile: "pnpm-lock.yaml"},
		},
		{
			name: "wildcard version is not reportable",
			files: map[string]string{
				"package.json": `{"name": "t", "devEngines": {"packageManager": {"name": "pnpm", "version": "*"}}}`,
			},
			want:         packageManager{name: "pnpm"},
			wantWarnings: []string{"devEngines.packageManager has a version this action cannot report; omitting it"},
		},
		{
			name: "malformed version is not reportable",
			files: map[string]string{
				"package.json": `{"name": "t", "packageManager": "pnpm@01.2.3"}`,
			},
			want:         packageManager{name: "pnpm"},
			wantWarnings: []string{"packageManager has a version this action cannot report; omitting it"},
		},
		{
			name: "tag version is not reportable",
			files: map[string]string{
				"package.json": `{"name": "t", "devEngines": {"packageManager": {"name": "pnpm", "version": "latest"}}}`,
			},
			want:         packageManager{name: "pnpm"},
			wantWarnings: []string{"devEngines.packageManager has a version this action cannot report; omitting it"},
		},
		{
			name: "both npm lockfiles",
			files: map[string]string{
				"package.json":        `{"name": "t"}`,
				"package-lock.json":   `{}`,
				"npm-shrinkwrap.json": `{}`,
			},
			want: packageManager{name: "npm", lockFile: "npm-shrinkwrap.json"},
		},
		{
			name: "both bun lockfiles",
			files: map[string]string{
				"package.json": `{"name": "t"}`,
				"bun.lockb":    "binary",
				"bun.lock":     `{}`,
			},
			want: packageManager{name: "bun", lockFile: "bun.lock"},
		},
		{
			name: "unsupported manager falls back to the lockfile",
			files: map[string]string{
				"package.json":   `{"name": "t", "packageManager": "cnpm@9.0.0"}`,
				"pnpm-lock.yaml": "lockfileVersion: '9.0'\n",
			},
			want:         packageManager{name: "pnpm", lockFile: "pnpm-lock.yaml"},
			wantWarnings: []string{"packageManager names an unsupported package manager; ignoring it"},
		},
		{
			name: "devEngines entry without a name",
			files: map[string]string{
				"package.json": `{"name": "t", "devEngines": {"packageManager": {"version": "10.0.0"}}}`,
			},
			want:         packageManager{name: "npm"},
			wantWarnings: []string{"devEngines.packageManager names no package manager; ignoring it"},
		},
		{
			name: "devEngines of the wrong shape",
			files: map[string]string{
				"package.json": `{"name": "t", "devEngines": {"packageManager": "pnpm"}}`,
			},
			want:         packageManager{name: "npm"},
			wantWarnings: []string{"devEngines.packageManager is neither an object nor a list of objects"},
		},
		{
			name: "version that is not reportable",
			files: map[string]string{
				"package.json": `{"name": "t", "packageManager": "yarn@https://example.com/yarn.tgz#sha"}`,
				".yarnrc.yml":  "nodeLinker: node-modules\n",
			},
			want:         packageManager{name: "yarn-berry"},
			wantWarnings: []string{"packageManager has a version this action cannot report; omitting it"},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got, warnings := detectProject(t, writeProject(t, tt.files))
			if got != tt.want {
				t.Errorf("got %+v, want %+v", got, tt.want)
			}
			if len(warnings) != len(tt.wantWarnings) {
				t.Fatalf("warnings = %q, want %d matching %q", warnings, len(tt.wantWarnings), tt.wantWarnings)
			}
			for i, want := range tt.wantWarnings {
				if !strings.Contains(warnings[i], want) {
					t.Errorf("warning %d = %q, want it to contain %q", i, warnings[i], want)
				}
			}
		})
	}
}

// A declared Yarn version decides between classic and Berry over what the
// files on disk suggest.
func TestYarnDeclaredVersionWins(t *testing.T) {
	tests := []struct {
		name  string
		files map[string]string
		want  string
	}{
		{"classic version beside a yarnrc", map[string]string{
			"package.json": `{"name": "t", "packageManager": "yarn@1.22.22"}`,
			".yarnrc.yml":  "nodeLinker: node-modules\n",
			"yarn.lock":    classicYarnLock,
		}, "yarn"},
		{"berry range in devEngines", map[string]string{
			"package.json": `{"name": "t", "devEngines": {"packageManager": {"name": "yarn", "version": "^4.0.0"}}}`,
		}, "yarn-berry"},
		{"no version, classic lockfile", map[string]string{
			"package.json": `{"name": "t", "devEngines": {"packageManager": {"name": "yarn"}}}`,
			"yarn.lock":    classicYarnLock,
		}, "yarn"},
		{"no version, berry lockfile", map[string]string{
			"package.json": `{"name": "t", "devEngines": {"packageManager": {"name": "yarn"}}}`,
			"yarn.lock":    berryYarnLock,
		}, "yarn-berry"},
		{"unbounded range falls back to files", map[string]string{
			"package.json": `{"name": "t", "devEngines": {"packageManager": {"name": "yarn", "version": "*"}}}`,
			".yarnrc.yml":  "nodeLinker: node-modules\n",
		}, "yarn-berry"},
		{"range spanning generations falls back to a berry lockfile", map[string]string{
			"package.json": `{"name": "t", "devEngines": {"packageManager": {"name": "yarn", "version": ">=1"}}}`,
			"yarn.lock":    berryYarnLock,
		}, "yarn-berry"},
		{"range spanning generations falls back to a classic lockfile", map[string]string{
			"package.json": `{"name": "t", "devEngines": {"packageManager": {"name": "yarn", "version": ">=1"}}}`,
			"yarn.lock":    classicYarnLock,
		}, "yarn"},
		{"alternation spanning generations falls back to files", map[string]string{
			"package.json": `{"name": "t", "devEngines": {"packageManager": {"name": "yarn", "version": "4 || 1"}}}`,
			"yarn.lock":    classicYarnLock,
		}, "yarn"},
		{"lower bound of 2 or more is berry", map[string]string{
			"package.json": `{"name": "t", "devEngines": {"packageManager": {"name": "yarn", "version": ">=2"}}}`,
			"yarn.lock":    classicYarnLock,
		}, "yarn-berry"},
		{"classic wildcard range is classic", map[string]string{
			"package.json": `{"name": "t", "devEngines": {"packageManager": {"name": "yarn", "version": "1.x"}}}`,
			".yarnrc.yml":  "nodeLinker: node-modules\n",
		}, "yarn"},
		{"upper bound below 2 is classic despite a yarnrc", map[string]string{
			"package.json": `{"name": "t", "devEngines": {"packageManager": {"name": "yarn", "version": "<2"}}}`,
			".yarnrc.yml":  "nodeLinker: node-modules\n",
		}, "yarn"},
		{"bounded classic range is classic despite a berry lockfile", map[string]string{
			"package.json": `{"name": "t", "devEngines": {"packageManager": {"name": "yarn", "version": ">=1 <2"}}}`,
			"yarn.lock":    berryYarnLock,
		}, "yarn"},
		{"berry alternation is berry despite a classic lockfile", map[string]string{
			"package.json": `{"name": "t", "devEngines": {"packageManager": {"name": "yarn", "version": "^2 || ^4"}}}`,
			"yarn.lock":    classicYarnLock,
		}, "yarn-berry"},
		{"classic hyphen range is classic", map[string]string{
			"package.json": `{"name": "t", "devEngines": {"packageManager": {"name": "yarn", "version": "1.0.0 - 1.22.22"}}}`,
			"yarn.lock":    berryYarnLock,
		}, "yarn"},
		{"unparsable range falls back to files", map[string]string{
			"package.json": `{"name": "t", "devEngines": {"packageManager": {"name": "yarn", "version": "stable"}}}`,
			"yarn.lock":    berryYarnLock,
		}, "yarn-berry"},
		{"empty range falls back to files", map[string]string{
			"package.json": `{"name": "t", "devEngines": {"packageManager": {"name": "yarn", "version": "1.20 - 1.10"}}}`,
			"yarn.lock":    berryYarnLock,
		}, "yarn-berry"},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got, _ := detectProject(t, writeProject(t, tt.files))
			if got.name != tt.want {
				t.Errorf("name = %q, want %q", got.name, tt.want)
			}
		})
	}
}

func TestAdmittedMajors(t *testing.T) {
	const inf = anyMajor
	tests := []struct {
		spec string
		want []majorRange // nil with ok false means unparsable
		ok   bool
	}{
		{"", []majorRange{{0, inf}}, true},
		{"*", []majorRange{{0, inf}}, true},
		{"x", []majorRange{{0, inf}}, true},
		{"4.5.0", []majorRange{{4, 4}}, true},
		{"v4.5.0", []majorRange{{4, 4}}, true},
		{"=4.5.0", []majorRange{{4, 4}}, true},
		{"4.5.0-rc.1", []majorRange{{4, 4}}, true},
		{"10", []majorRange{{10, 10}}, true},
		{"10.x", []majorRange{{10, 10}}, true},
		{"10.*.*", []majorRange{{10, 10}}, true},
		{"^10.1", []majorRange{{10, 10}}, true},
		{"^0.3.1", []majorRange{{0, 0}}, true},
		{"~1.22.0", []majorRange{{1, 1}}, true},
		{">=2", []majorRange{{2, inf}}, true},
		{">= 10.1", []majorRange{{10, inf}}, true},
		{">1", []majorRange{{2, inf}}, true},
		{">1.2", []majorRange{{1, inf}}, true},
		{">1.2.3", []majorRange{{1, inf}}, true},
		{"<2", []majorRange{{0, 1}}, true},
		{"<2.0.0", []majorRange{{0, 1}}, true},
		{"<2.1", []majorRange{{0, 2}}, true},
		{"<=2", []majorRange{{0, 2}}, true},
		{">=1 <2", []majorRange{{1, 1}}, true},
		{">=9 <=10.3", []majorRange{{9, 10}}, true},
		{"1.0.0 - 1.22.22", []majorRange{{1, 1}}, true},
		{"1 - 3", []majorRange{{1, 3}}, true},
		{"^2 || ^4", []majorRange{{2, 2}, {4, 4}}, true},
		{"<1 || >=3", []majorRange{{0, 0}, {3, inf}}, true},
		{">=3 <2", nil, true},
		{"<0", nil, true},
		{"1.20 - 1.10", nil, true},
		{">=1.20 <1.10", nil, true},
		{">1.9.9 <2", []majorRange{{1, 1}}, true},
		{"<=1.0.0", []majorRange{{0, 1}}, true},
		{"<2.0.1", []majorRange{{0, 2}}, true},
		{"~1", []majorRange{{1, 1}}, true},
		{"^0.0", []majorRange{{0, 0}}, true},
		{"^1.2.3 <1.2.0", nil, true},
		{"1.2.3+build.5", []majorRange{{1, 1}}, true},
		{"latest", nil, false},
		{"=>1", nil, false},
		{"1.2.3.4", nil, false},
		{"01.2.3", nil, false},
		{"1.02", nil, false},
		{"1.2.3-", nil, false},
		{"1.2.3-rc..1", nil, false},
		{"1.2.3-01", nil, false},
		{"1.2-rc.1", nil, false},
		{"1.2.3+", nil, false},
		{"=v1.2.3-rc.0+build.5", []majorRange{{1, 1}}, true},
		{"https://example.com/yarn.tgz", nil, false},
	}
	for _, tt := range tests {
		got, ok := admittedMajors(tt.spec)
		if ok != tt.ok || !slices.Equal(got, tt.want) {
			t.Errorf("admittedMajors(%q) = %v, %t; want %v, %t", tt.spec, got, ok, tt.want, tt.ok)
		}
	}
}

func TestSingleMajor(t *testing.T) {
	for _, tt := range []struct {
		ranges []majorRange
		want   int
		ok     bool
	}{
		{[]majorRange{{4, 4}}, 4, true},
		{[]majorRange{{4, 4}, {4, 4}}, 4, true},
		{[]majorRange{{4, 5}}, 0, false},
		{[]majorRange{{4, 4}, {5, 5}}, 0, false},
		{nil, 0, false},
	} {
		got, ok := singleMajor(tt.ranges)
		if got != tt.want || ok != tt.ok {
			t.Errorf("singleMajor(%v) = %d, %t; want %d, %t", tt.ranges, got, ok, tt.want, tt.ok)
		}
	}
}

func TestPnpmWorkspace(t *testing.T) {
	tests := []struct {
		name           string
		files          map[string]string
		wantWorkspaces []string
	}{
		{
			name: "pnpm-workspace.yaml only",
			files: map[string]string{
				"package.json":        `{"name": "t"}`,
				"pnpm-workspace.yaml": "packages:\n  - packages/*\n  - apps/*\n",
			},
			wantWorkspaces: []string{"packages/*", "apps/*"},
		},
		{
			name: "both sources are merged without duplicates",
			files: map[string]string{
				"package.json":        `{"name": "t", "workspaces": ["packages/*", "tools/*"]}`,
				"pnpm-workspace.yaml": "packages:\n  - packages/*\n  - apps/*\n  - '!**/test/**'\n",
			},
			wantWorkspaces: []string{"packages/*", "tools/*", "apps/*", "!**/test/**"},
		},
		{
			name: "settings without packages",
			files: map[string]string{
				"package.json":        `{"name": "t"}`,
				"pnpm-workspace.yaml": "onlyBuiltDependencies:\n  - esbuild\n",
			},
		},
		{
			name: "malformed pnpm-workspace.yaml",
			files: map[string]string{
				"package.json":        `{"name": "t", "workspaces": ["packages/*"]}`,
				"pnpm-workspace.yaml": "packages: [unclosed\n",
			},
			wantWorkspaces: []string{"packages/*"},
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			metadata, err := NewExtractor().Extract(writeProject(t, tt.files))
			if err != nil {
				t.Fatal(err)
			}
			isWorkspace, _ := metadata.LanguageSpecific["is_workspace"].(bool)
			if isWorkspace != (len(tt.wantWorkspaces) > 0) {
				t.Errorf("is_workspace = %t, want %t", isWorkspace, len(tt.wantWorkspaces) > 0)
			}
			workspaces, _ := metadata.LanguageSpecific["workspaces"].([]string)
			if !slices.Equal(workspaces, tt.wantWorkspaces) {
				t.Errorf("workspaces = %q, want %q", workspaces, tt.wantWorkspaces)
			}
			if len(tt.wantWorkspaces) > 0 && metadata.LanguageSpecific["workspace_count"] != len(tt.wantWorkspaces) {
				t.Errorf("workspace_count = %v, want %d", metadata.LanguageSpecific["workspace_count"], len(tt.wantWorkspaces))
			}
		})
	}
}

func TestReadPnpmWorkspaceRejectsMalformedFile(t *testing.T) {
	dir := writeProject(t, map[string]string{"pnpm-workspace.yaml": "packages: [unclosed\n"})
	if _, err := readPnpmWorkspace(dir); err == nil {
		t.Error("readPnpmWorkspace accepted a malformed file")
	}
}

// The fixtures under testdata exercise the lockfiles and workspace file
// this extractor once missed, through the full extraction path.
func TestPackageManagerFixtures(t *testing.T) {
	tests := []struct {
		fixture string
		want    map[string]interface{}
		absent  []string
	}{
		{"bun-text", map[string]interface{}{
			"package_manager": "bun",
			"lock_file":       "bun.lock",
			"has_lock_file":   true,
		}, []string{"package_manager_version", "is_workspace"}},
		{"npm-shrinkwrap", map[string]interface{}{
			"package_manager": "npm",
			"lock_file":       "npm-shrinkwrap.json",
			"has_lock_file":   true,
		}, []string{"package_manager_version", "is_workspace"}},
		{"pnpm-workspace", map[string]interface{}{
			"package_manager":         "pnpm",
			"package_manager_version": "10.18.0",
			"lock_file":               "pnpm-lock.yaml",
			"has_lock_file":           true,
			"is_workspace":            true,
			"workspace_count":         2,
		}, nil},
	}
	for _, tt := range tests {
		t.Run(tt.fixture, func(t *testing.T) {
			metadata, err := NewExtractor().Extract(filepath.Join("testdata", tt.fixture))
			if err != nil {
				t.Fatal(err)
			}
			for key, want := range tt.want {
				if got := metadata.LanguageSpecific[key]; got != want {
					t.Errorf("%s = %v, want %v", key, got, want)
				}
			}
			for _, key := range tt.absent {
				if got, ok := metadata.LanguageSpecific[key]; ok {
					t.Errorf("%s = %v, want it absent", key, got)
				}
			}
		})
	}
}
